<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \BA\MeilisearchFrontendMinimal\ViewModel\SearchForm $viewModel */
$query = '';
$viewModel = $block->getViewModel();
$action = $viewModel ? $viewModel->getCatalogSearchActionUrl() : '/catalogsearch/result/';
?>
<div class="block-search">
    <form class="form minisearch" action="<?= $escaper->escapeUrl($action) ?>" method="get">
        <div class="field search">
            <label class="label" for="search">
                <span><?= $escaper->escapeHtml(__('Search')) ?></span>
            </label>
            <div class="control">
                <input id="search" type="text" name="q" value="<?= $escaper->escapeHtmlAttr($query) ?>" placeholder="<?=  __('Search') ?>" class="input-text" autocomplete="off" />
            </div>
        </div>
        <div class="actions">
            <button type="submit" class="action search primary">
                <span><?= $escaper->escapeHtml(__('Search')) ?></span>
            </button>
        </div>
    </form>
</div>
