<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Walkwizus\MeilisearchFrontend\ViewModel\Ssr $viewModel
 * @var \Magento\Framework\Escaper $escaper
 */
$viewModel = $block->getViewModel();
$config = $viewModel->getConfig();
$searchResult = $viewModel->getSearchResult();
$totalHits = (int)($searchResult['totalHits'] ?? 0);
$productListMode = $viewModel->getProductListMode();
$imageAttribute = $config['images']['category_page_' . $productListMode]['type'];
$imageWidth = $config['images']['category_page_' . $productListMode]['width'];
$imageHeight = $config['images']['category_page_' . $productListMode]['height'];
?>
<?php if ($totalHits === 0): ?>
    <div id="meilisearch-frontend-search-ssr">
        <div class="message info empty">
            <div><?= $escaper->escapeHtml(__("We can't find products matching the selection.")) ?></div>
        </div>
    </div>
<?php else: ?>
    <div id="meilisearch-frontend-search-ssr">
        <div class="products wrapper <?= $productListMode ?> products-<?= $productListMode ?>">
            <ol class="products list items product-items">
                <?php foreach ($searchResult['hits'] as $hit): ?>
                <li class="item product product-item">
                    <div class="product-item-info">
                        <a href="<?= $viewModel->getProductUrl($hit['url_key']) ?>" class="product photo product-item-photo">
                            <span class="product-image-container" style="width: 240px;">
                                <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                    <img src="<?= $viewModel->getProductImage($hit[$imageAttribute]) ?>" alt="<?= $hit['name'] ?>" class="product-image-photo" loading="lazy" width="<?= $imageWidth ?>>" height="<?= $imageHeight ?>" />
                                </span>
                            </span>
                        </a>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name">
                                <a href="<?= $viewModel->getProductUrl($hit['url_key']) ?>" class="product-item-link">
                                    <?= $hit['name'] ?>
                                </a>
                            </strong>
                            <?= $viewModel->getProductPrice($hit[$config['priceAttributeCode']]) ?>
                        </div>
                    </div>
                </li>
                <?php endforeach; ?>
            </ol>
        </div>
        <div class="toolbar toolbar-products">
            <?php
                $pagination = $block
                    ->getChildBlock('meilisearch.frontend.search.pagination')
                    ->setData('config', $config)
                    ->setData('searchResult', $searchResult);
            ?>
            <?= $pagination->toHtml(); ?>
        </div>
    </div>
<?php endif; ?>
<div id="meilisearch-frontend-search" data-bind="scope: 'meilisearch-frontend-search'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Walkwizus_MeilisearchFrontend/js/components/boot": {
                    "initialState": <?= /* @noEscape */ json_encode($searchResult) ?>
                }
            },
            "#meilisearch-frontend-search": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?: '{}' ?>
        }
    }
</script>
