<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<div id="meilisearch-frontend-search" data-bind="scope: 'meilisearch-frontend-search'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Walkwizus_MeilisearchFrontend/js/components/boot": {}
        },
        "#meilisearch-frontend-search": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?: '{}' ?>
        }
    }
</script>
