<div>
    <p>
        Comma-separated list of stop words.
    </p>
    <p>
        Stop words are strongly related to the language used in your dataset.
        For example, most datasets containing English documents will have countless occurrences of <strong>the</strong> and <strong>of</strong>.
        Italian datasets, instead, will benefit from ignoring words like <strong>a</strong>, <strong>la</strong>, or <strong>il</strong>.
    </p>
    <ul>
        <li>
            <a href="https://www.meilisearch.com/docs/learn/getting_started/indexes#stop-words" target="_blank">Stop words documentation</a>
        </li>
        <li>
            <a href="https://github.com/stopwords-iso/stopwords-iso" target="_blank">This open-source project on GitHub</a>
            offers lists of possible stop words in different languages. Note that, depending on your dataset and use case, you will need to tweak these lists for optimal results.
        </li>
    </ul>
</div>
